build:
	cl /EHsc *.cpp /link /out:Main.exe

clean:
	@IF EXIST "Main.exe" del "Main.exe" > NUL
	@IF EXIST "Main.obj" del "Main.obj" > NUL
	@IF EXIST "MinimaxBenchmarker.obj" del "MinimaxBenchmarker.obj" > NUL
	@IF EXIST "TicTacToeMinimax.obj" del "TicTacToeMinimax.obj" > NUL
